[project]
name = "vgiskill_custom_app"
version = "0.0.1"
description = "Custom extensions and APIs for Frappe LMS"
readme = ""
requires-python = ">=3.10"
dependencies = [
  "frappe",
]

[tool.setuptools]
packages = ["vgiskill_custom_app"]
